export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'oav-bg':            'var(--oav-bg)',
        'oav-surface':       'var(--oav-surface)',
        'oav-surface-2':     'var(--oav-surface-2)',
        'oav-border':        'var(--oav-border)',
        'oav-text':          'var(--oav-text)',
        'oav-muted':         'var(--oav-muted)',
        'oav-accent':        'var(--oav-accent)',
        'oav-accent-2':      'var(--oav-accent-2)',
        'oav-success':       'var(--oav-success)',
        'oav-error':         'var(--oav-error)',
        'oav-warning':       'var(--oav-warning)',
        'oav-selected':      'var(--oav-selected)',
        'oav-hover':         'var(--oav-hover)',
        'oav-glow':          'var(--oav-glow)',
        'oav-disabled':      'var(--oav-disabled)',
        'oav-disabled-text': 'var(--oav-disabled-text)',
        'oav-focus':         'var(--oav-focus)',
        'oav-glass-bg':      'var(--oav-glass-bg)',
        'oav-glass-border':  'var(--oav-glass-border)',
        'oav-skeleton':      'var(--oav-skeleton)',
        'oav-skeleton-shine':'var(--oav-skeleton-shine)',
      },
      backdropBlur: { xs: '2px' },
    },
  },
  plugins: [],
};
